'use client';

import { createContext, useContext, useState, useEffect } from 'react';

// Translation keys for all UI text across the site
const translations = {
  en: {
    // Nav
    sport: 'Sport', history: 'History', arts: 'Arts', classics: 'Classics', nature: 'Nature', cook: 'Cook', home: 'Home',
    // Main page
    tagline: 'The world in 30 seconds. News without the noise.',
    promise1: 'Only news, sourced and checked.',
    promise2: 'Ask. Follow up. Understand.',
    charterTitle: 'Our values.',
    charter1label: 'What we believe in.',
    charter1: 'International humanitarian law. The Universal Declaration of Human Rights. The Geneva Conventions. Applied equally. No exceptions.',
    charter2label: 'Why we do this.',
    charter2: 'There is too much information out there. It is impossible to know what to trust.',
    charter3label: 'Why trust MIWO?',
    charter3: 'We believe truth still exists. No party, no sponsor. Just facts.',
    charterLink: 'Read the full charter',
    rightNow: 'Right now',
    prompt1: 'What\'s happening right now?',
    prompt2: 'Catch me up',
    prompt3: 'Was passiert gerade?',
    talkTo: 'Talk to MIWO...',
    voice: 'Voice',
    // Sport
    sportLabel: 'Sport', sportTitle: 'Every match.\nEvery moment.',
    sportSub: 'Live scores, deep analysis, and the stories that matter. From football pitches to racing circuits, from underdogs to dynasties — the sport that shapes how we understand the world.',
    sportPlaceholder: 'Ask about any sport, match, or athlete...',
    // History
    historyLabel: 'History', historyTitle: 'History isn\'t just\nwhat happened.',
    historySub: 'Ancient empires, medieval kingdoms, revolutions that shook everything. And the stories we tell ourselves about why it mattered. Understanding the past is the only way to understand now.',
    historyPlaceholder: 'Ask about any era, event, or figure...',
    // Classics
    classicsLabel: 'Classics', classicsTitle: 'Everything old\nis new again.',
    classicsSub: 'Ancient Rome and Greece. Philosophy that still hits. Literature that changed everything. Politics, culture, ideas that somehow got everything right thousands of years ago and we\'re still figuring out what they meant.',
    classicsPlaceholder: 'Ask about Rome, Greece, philosophy, Plato, Aristotle, Stoicism...',
    // Arts
    artsLabel: 'Arts & Culture', artsTitle: 'Art is how we\nunderstand now.',
    artsSub: 'Visual arts, music, theatre, film — the stuff that makes us human. From gallery openings to movements that shake the world. Because culture is where everything real happens.',
    artsPlaceholder: 'Ask about arts, music, theatre, culture...',
    // Nature
    natureLabel: 'Nature', natureTitle: 'The planet speaks.\nAre we listening?',
    natureSub: 'Climate. Oceans. Forests. Energy. The environmental stories that change everything. Told with science. No greenwash. No false hope. Just what\'s really happening.',
    naturePlaceholder: 'Ask about climate, biodiversity, energy, nature...',
    // Cook
    cookLabel: 'Cook', cookTitle: 'Every meal tells\na story.',
    cookSub: 'Recipes, techniques, ingredients — the culture, history, and joy behind what we eat. From weeknight quick fixes to centuries of tradition. Because food is never just food.',
    cookPlaceholder: 'Ask about any recipe, technique, cuisine, or ingredient...',
    pantryTitle: 'What\u2019s in your kitchen?',
    pantrySub: 'Type your ingredients separated by commas, or tap the chips below. We\u2019ll suggest what you can cook right now.',
    pantryAdd: '+ Add',
    pantryFind: 'Find Recipes',
    // Impressum
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'All rights reserved.',
    trademark: 'and the MIWO name and logo are trademarks of Tindra Film GbR. Content generated by MIWO is for informational purposes only and does not constitute professional advice. All editorial output is AI-assisted and should be independently verified.',
    coFounder: 'Co-Founder',
    miwoDesc: 'My World. A daily news check-in for people who gave up on the news. Fast, honest, global.',
    // Filters
    allSport: 'All Sport', allArts: 'All Arts', allNature: 'All Nature',
    allHistory: 'All History',
    // Common
    you: 'You',
    stories: 'Stories',
    askMiwo: 'Ask MIWO',
    readMore: 'Read more',
    askMiwoAbout: 'Ask MIWO about this',
    whatDoYouHave: 'What do you have?',
    dailyFeature: 'Daily Feature',
    cowardsTitle: 'Cowards We Should Remember',
    cowardsSub: 'History is full of heroes. It\u2019s also full of people who knew what was right, had the power to act, and chose not to. Today\u2019s story',
    backToBriefing: 'Back to briefing',
    errorMessage: 'Something went wrong. Try again in a moment.',
  },
  de: {
    sport: 'Sport', history: 'Geschichte', arts: 'Kunst', classics: 'Klassik', nature: 'Natur', cook: 'Kochen', home: 'Start',
    tagline: 'Die Welt in 30 Sekunden. Nachrichten ohne L\u00E4rm.',
    promise1: 'Nur Nachrichten, recherchiert und gepr\u00FCft.',
    promise2: 'Fragen. Nachhaken. Verstehen.',
    charterTitle: 'Unsere Werte.',
    charter1label: 'Woran wir glauben.',
    charter1: 'Humanitäres Völkerrecht. Die Allgemeine Erklärung der Menschenrechte. Die Genfer Konventionen. Für alle gleich. Ohne Ausnahme.',
    charter2label: 'Warum wir das tun.',
    charter2: 'Es gibt zu viele Informationen da draußen. Es ist unmöglich zu wissen, was man glauben kann.',
    charter3label: 'Warum MIWO vertrauen?',
    charter3: 'Wir glauben, dass es Wahrheit noch gibt. Keine Partei, kein Sponsor. Nur Fakten.',
    charterLink: 'Die vollständige Charta lesen',
    rightNow: 'Gerade jetzt',
    prompt1: 'Was passiert gerade?',
    prompt2: 'Bring mich auf den Stand',
    prompt3: 'Was passiert gerade in Europa?',
    talkTo: 'Sprich mit MIWO...',
    voice: 'Stimme',
    sportLabel: 'Sport', sportTitle: 'Jedes Spiel.\nJeder Moment.',
    sportSub: 'Live-Ergebnisse, tiefe Analysen und die Geschichten, die zählen. Von Fußballplätzen bis zu Rennstrecken, von Außenseitern bis zu Dynastien — der Sport, der zeigt, wie wir die Welt verstehen.',
    sportPlaceholder: 'Frag nach Sport, Spielen oder Athleten...',
    historyLabel: 'Geschichte', historyTitle: 'Geschichte ist nicht nur\nwas geschah.',
    historySub: 'Antike Imperien, mittelalterliche Königreiche, Revolutionen, die alles verändert haben. Und die Geschichten, die wir uns über die Bedeutung erzählen. Die Vergangenheit verstehen ist der einzige Weg, um jetzt zu verstehen.',
    historyPlaceholder: 'Frag nach einer Epoche, einem Ereignis oder einer Person...',
    classicsLabel: 'Klassik', classicsTitle: 'Alles Alte\nist neu.',
    classicsSub: 'Antikes Rom und Griechenland. Philosophie, die immer noch wirkt. Literatur, die alles ver\u00E4ndert hat. Politik und Ideen, die vor Tausenden von Jahren alles richtig verstanden haben und wir versuchen immer noch, sie zu begreifen.',
    classicsPlaceholder: 'Frag nach Rom, Griechenland, Philosophie, Platon, Aristoteles, Stoizismus...',
    artsLabel: 'Kunst & Kultur', artsTitle: 'Kunst ist wie wir\njetzt verstehen.',
    artsSub: 'Bildende Kunst, Musik, Theater, Film — das Zeug, das uns menschlich macht. Von Galerieöffnungen bis zu Bewegungen, die die Welt erschüttern. Denn Kultur ist dort, wo wirklich alles passiert.',
    artsPlaceholder: 'Frag nach Kunst, Musik, Theater, Kultur...',
    natureLabel: 'Natur', natureTitle: 'Der Planet spricht.\nH\u00F6ren wir zu?',
    natureSub: 'Klima. Ozeane. W\u00E4lder. Energie. Die Umweltgeschichten, die alles verändern. Erzählt mit Wissenschaft. Ohne Greenwashing. Ohne falsche Hoffnung. Nur das, was wirklich passiert.',
    naturePlaceholder: 'Frag nach Klima, Biodiversit\u00E4t, Energie, Natur...',
    cookLabel: 'Kochen', cookTitle: 'Jedes Essen erzählt\neine Geschichte.',
    cookSub: 'Rezepte, Techniken, Zutaten — die Kultur, Geschichte und Freude hinter dem, was wir essen. Von schnellen Wochentags-Mahlzeiten bis zu jahrhundertealten Traditionen. Denn Essen ist nie nur Essen.',
    cookPlaceholder: 'Frag nach Rezepten, Techniken, K\u00FCche oder Zutaten...',
    pantryTitle: 'Was hast du in der K\u00FCche?',
    pantrySub: 'Gib deine Zutaten durch Kommas getrennt ein oder tippe auf die Chips unten.',
    pantryAdd: '+ Hinzuf\u00FCgen',
    pantryFind: 'Rezepte finden',
    impressum: 'Impressum', legal: 'Rechtliches',
    allRights: 'Alle Rechte vorbehalten.',
    trademark: 'und der MIWO-Name und das Logo sind Marken der Tindra Film GbR. Von MIWO generierte Inhalte dienen nur zu Informationszwecken.',
    coFounder: 'Mitgr\u00FCnder/in',
    miwoDesc: 'Meine Welt. Ein konversationeller Nachrichtenintelligenz-Dienst \u2014 gebaut, um durch Lärm zu schneiden, Desinformation zu bek\u00E4mpfen und Tiefe zu liefern.',
    allSport: 'Alle Sportarten', allArts: 'Alle Kunst', allNature: 'Alle Natur',
    allHistory: 'Alle Geschichte',
    you: 'Du',
    stories: 'Beitr\u00E4ge',
    askMiwo: 'Frag MIWO',
    readMore: 'Weiterlesen',
    askMiwoAbout: 'MIWO dazu fragen',
    whatDoYouHave: 'Was hast du da?',
    dailyFeature: 'Tagesrubrik',
    cowardsTitle: 'Feiglinge, an die wir uns erinnern sollten',
    cowardsSub: 'Die Geschichte ist voller Helden. Sie ist auch voller Menschen, die wussten, was richtig war, die Macht hatten zu handeln, und es nicht taten.',
    backToBriefing: 'Zur\u00FCck zum Briefing',
    errorMessage: 'Etwas ist schiefgelaufen. Versuche es gleich nochmal.',
  },
  es: {
    sport: 'Deporte', history: 'Historia', arts: 'Arte', classics: 'Cl\u00E1sicos', nature: 'Naturaleza', cook: 'Cocina', home: 'Inicio',
    tagline: 'El mundo en 30 segundos. Noticias sin ruido.',
    promise1: 'Solo noticias, verificadas y contrastadas.',
    promise2: 'Pregunta. Profundiza. Comprende.',
    charterTitle: 'Nuestros valores.',
    charter1label: 'En lo que creemos.',
    charter1: 'El derecho internacional humanitario. La Declaración Universal de los Derechos Humanos. Los Convenios de Ginebra. Aplicados por igual. Sin excepciones.',
    charter2label: 'Por qué hacemos esto.',
    charter2: 'Hay demasiada información ahí fuera. Es imposible saber en qué confiar.',
    charter3label: '¿Por qué confiar en MIWO?',
    charter3: 'Creemos que la verdad aún existe. Sin partido, sin patrocinador. Solo hechos.',
    charterLink: 'Leer la carta editorial completa',
    rightNow: 'Ahora mismo',
    prompt1: '¿Qué está pasando ahora?',
    prompt2: 'Ponme al d\u00EDa',
    prompt3: '\u00BFQu\u00E9 pas\u00F3 hoy en Am\u00E9rica Latina?',
    talkTo: 'Habla con MIWO...',
    voice: 'Voz',
    sportLabel: 'Deporte', sportTitle: 'Cada partido.\nCada momento.',
    sportSub: 'Resultados en vivo, análisis profundo y las historias que importan. De los campos de fútbol a las pistas de carreras. Porque el deporte es cómo entendemos el mundo.',
    sportPlaceholder: 'Pregunta sobre deportes, partidos o atletas...',
    historyLabel: 'Historia', historyTitle: 'La historia no es solo\nqué pasó.',
    historySub: 'Imperios antiguos, reinos medievales, revoluciones que lo cambiaron todo. Y las historias que nos contamos sobre por qué importó. Entender el pasado es la única forma de entender ahora.',
    historyPlaceholder: 'Pregunta sobre cualquier \u00E9poca, evento o figura...',
    classicsLabel: 'Cl\u00E1sicos', classicsTitle: 'Todo lo antiguo\nes nuevo otra vez.',
    classicsSub: 'Roma y Grecia antiguas. Filosof\u00EDa que a\u00FAn resuena. Literatura que lo cambi\u00F3 todo. Ideas de hace miles de a\u00F1os que de alguna manera acertaron en todo, y a\u00FAn estamos intentando entender qu\u00E9 quisieron decir.',
    classicsPlaceholder: 'Pregunta sobre Roma, Grecia, filosof\u00EDa, Plat\u00F3n, Arist\u00F3teles...',
    artsLabel: 'Arte y Cultura', artsTitle: 'El arte es cómo\nentendemos ahora.',
    artsSub: 'Artes visuales, música, teatro, cine — lo que nos hace humanos. De galerías a movimientos que sacuden el mundo. Porque la cultura es donde realmente sucede todo.',
    artsPlaceholder: 'Pregunta sobre arte, m\u00FAsica, teatro, cultura...',
    natureLabel: 'Naturaleza', natureTitle: 'El planeta habla.\n¿Estamos escuchando?',
    natureSub: 'Clima. Océanos. Bosques. Energía. Las historias ambientales que lo cambian todo. Contadas con ciencia. Sin greenwashing. Sin falsas esperanzas. Solo lo que está pasando realmente.',
    naturePlaceholder: 'Pregunta sobre clima, biodiversidad, energ\u00EDa...',
    cookLabel: 'Cocina', cookTitle: 'Cada comida cuenta\nuna historia.',
    cookSub: 'Recetas, técnicas, ingredientes — la cultura, historia y alegría detrás de lo que comemos. Desde comidas rápidas de la semana hasta tradiciones centenarias. Porque la comida nunca es solo comida.',
    cookPlaceholder: 'Pregunta sobre recetas, t\u00E9cnicas, cocina o ingredientes...',
    pantryTitle: '\u00BFQu\u00E9 tienes en la cocina?',
    pantrySub: 'Escribe tus ingredientes separados por comas o toca las etiquetas.',
    pantryAdd: '+ A\u00F1adir',
    pantryFind: 'Buscar recetas',
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'Todos los derechos reservados.',
    trademark: 'y el nombre y logotipo de MIWO son marcas registradas de Tindra Film GbR.',
    coFounder: 'Cofundador/a',
    miwoDesc: 'Mi Mundo. Un servicio de inteligencia de noticias conversacional.',
    allSport: 'Todo Deporte', allArts: 'Todo Arte', allNature: 'Toda Naturaleza',
    allHistory: 'Toda Historia',
    you: 'T\u00FA',
    stories: 'Historias',
    askMiwo: 'Pregunta a MIWO',
    readMore: 'Leer m\u00E1s',
    askMiwoAbout: 'Preguntar a MIWO sobre esto',
    whatDoYouHave: '\u00BFQu\u00E9 tienes?',
    dailyFeature: 'Secci\u00F3n del d\u00EDa',
    cowardsTitle: 'Cobardes que debemos recordar',
    cowardsSub: 'La historia est\u00E1 llena de h\u00E9roes. Tambi\u00E9n est\u00E1 llena de personas que sab\u00EDan lo correcto, ten\u00EDan el poder de actuar, y eligieron no hacerlo.',
    backToBriefing: 'Volver al briefing',
    errorMessage: 'Algo sali\u00F3 mal. Int\u00E9ntalo de nuevo en un momento.',
  },
  fr: {
    sport: 'Sport', history: 'Histoire', arts: 'Arts', classics: 'Classiques', nature: 'Nature', cook: 'Cuisine', home: 'Accueil',
    tagline: 'Le monde en 30 secondes. L\u2019info sans le bruit.',
    promise1: 'Rien que l\u2019info, v\u00E9rifi\u00E9e et sourc\u00E9e.',
    promise2: 'Demandez. Creusez. Comprenez.',
    charterTitle: 'Nos valeurs.',
    charter1label: 'Ce en quoi nous croyons.',
    charter1: 'Le droit international humanitaire. La Déclaration universelle des droits de l\u2019homme. Les Conventions de Genève. Appliqués de manière égale. Sans exception.',
    charter2label: 'Pourquoi nous faisons cela.',
    charter2: 'Il y a trop d\u2019informations. Il est impossible de savoir à quoi faire confiance.',
    charter3label: 'Pourquoi faire confiance à MIWO\u00A0?',
    charter3: 'Nous croyons que la vérité existe encore. Pas de parti, pas de sponsor. Juste des faits.',
    charterLink: 'Lire la charte éditoriale complète',
    rightNow: 'En ce moment',
    prompt1: 'Que se passe-t-il en ce moment\u00A0?',
    prompt2: 'Mets-moi \u00E0 jour',
    prompt3: 'Quoi de neuf en Afrique francophone\u00A0?',
    talkTo: 'Parlez \u00E0 MIWO...',
    voice: 'Voix',
    sportLabel: 'Sport', sportTitle: 'Chaque match.\nChaque moment.',
    sportSub: 'Résultats en direct, analyses profondes et les histoires qui comptent. Des terrains de football aux circuits de course. Parce que le sport est comment nous comprenons le monde.',
    sportPlaceholder: 'Posez une question sur le sport, un match ou un athl\u00E8te...',
    historyLabel: 'Histoire', historyTitle: 'L\'histoire n\'est pas juste\nce qui s\'est passé.',
    historySub: 'Empires antiques, royaumes médiévaux, révolutions qui ont tout changé. Et les histoires que nous nous racontons sur pourquoi cela comptait. Comprendre le passé est le seul moyen de comprendre maintenant.',
    historyPlaceholder: 'Posez une question sur une \u00E9poque, un \u00E9v\u00E9nement ou un personnage...',
    classicsLabel: 'Classiques', classicsTitle: 'Tout ce qui est ancien\nest nouveau.',
    classicsSub: 'Rome et Gr\u00E8ce antiques. La philosophie qui r\u00E9sonne encore. La litt\u00E9rature qui a tout chang\u00E9. Des id\u00E9es d\u2019il y a des milliers d\u2019ann\u00E9es qui avaient tout compris, et nous essayons encore de comprendre ce qu\u2019elles voulaient dire.',
    classicsPlaceholder: 'Posez une question sur Rome, la Gr\u00E8ce, la philosophie, Platon, Aristote...',
    artsLabel: 'Arts et Culture', artsTitle: 'L\'art est comment nous\ncomprenons maintenant.',
    artsSub: 'Arts visuels, musique, théâtre, cinéma — ce qui nous rend humains. Des ouvertures de galeries aux mouvements qui ébranlent le monde. Parce que la culture est où tout se passe vraiment.',
    artsPlaceholder: 'Posez une question sur les arts, la musique, le th\u00E9\u00E2tre...',
    natureLabel: 'Nature', natureTitle: 'La planète parle.\nÉcoutons-nous?',
    natureSub: 'Climat. Océans. Forêts. Énergie. Les histoires environnementales qui changent tout. Racontées avec science. Pas de greenwashing. Pas de faux espoir. Juste ce qui se passe vraiment.',
    naturePlaceholder: 'Posez une question sur le climat, la biodiversit\u00E9, l\u2019\u00E9nergie...',
    cookLabel: 'Cuisine', cookTitle: 'Chaque repas raconte\nune histoire.',
    cookSub: 'Recettes, techniques, ingrédients — la culture, l\'histoire et la joie derrière ce que nous mangeons. Des repas rapides entre semaine aux traditions centenaires. Parce que la nourriture n\'est jamais juste de la nourriture.',
    cookPlaceholder: 'Posez une question sur les recettes, techniques, cuisine...',
    pantryTitle: 'Qu\u2019avez-vous dans la cuisine\u00A0?',
    pantrySub: 'Tapez vos ingr\u00E9dients s\u00E9par\u00E9s par des virgules ou touchez les puces.',
    pantryAdd: '+ Ajouter',
    pantryFind: 'Trouver des recettes',
    impressum: 'Mentions l\u00E9gales', legal: 'L\u00E9gal',
    allRights: 'Tous droits r\u00E9serv\u00E9s.',
    trademark: 'et le nom et logo MIWO sont des marques de Tindra Film GbR.',
    coFounder: 'Cofondateur/trice',
    miwoDesc: 'Mon Monde. Un service d\u2019intelligence m\u00E9diatique conversationnel.',
    allSport: 'Tous les Sports', allArts: 'Tous les Arts', allNature: 'Toute la Nature',
    allHistory: 'Toute l\u2019Histoire',
    you: 'Vous',
    stories: 'Articles',
    askMiwo: 'Demander \u00E0 MIWO',
    readMore: 'Lire la suite',
    askMiwoAbout: 'Demander \u00E0 MIWO',
    whatDoYouHave: 'Qu\u2019avez-vous\u00A0?',
    dailyFeature: 'Rubrique du jour',
    cowardsTitle: 'L\u00E2ches dont il faut se souvenir',
    cowardsSub: 'L\u2019histoire est pleine de h\u00E9ros. Elle est aussi pleine de gens qui savaient ce qui \u00E9tait juste, avaient le pouvoir d\u2019agir, et ont choisi de ne pas le faire.',
    backToBriefing: 'Retour au briefing',
    errorMessage: 'Quelque chose s\u2019est mal pass\u00E9. R\u00E9essayez dans un instant.',
  },
  ar: {
    sport: 'رياضة', history: 'تاريخ', arts: 'فنون', classics: 'كلاسيكيات', nature: 'طبيعة', cook: 'طبخ', home: 'الرئيسية',
    tagline: 'العالم في ٣٠ ثانية. الأخبار بدون ضوضاء.',
    promise1: 'أخبار فقط، موثقة وموثوقة.',
    promise2: 'اسأل. تابع. افهم.',
    charterTitle: 'قيمنا.',
    charter1label: 'ما نؤمن به.',
    charter1: 'القانون الدولي الإنساني. الإعلان العالمي لحقوق الإنسان. اتفاقيات جنيف. تُطبّق بالتساوي. بلا استثناء.',
    charter2label: 'لماذا نفعل هذا.',
    charter2: 'هناك الكثير من المعلومات. من المستحيل معرفة ما يمكن الوثوق به.',
    charter3label: 'لماذا تثق بـ MIWO؟',
    charter3: 'نؤمن أن الحقيقة لا تزال موجودة. لا حزب، لا راعٍ. فقط حقائق.',
    charterLink: 'اقرأ الميثاق التحريري كاملاً',
    rightNow: 'الآن',
    prompt1: 'ماذا يحدث الآن؟',
    prompt2: 'أعطني الملخص العالمي',
    prompt3: 'ما الجديح في الشرق الأوسط؟',
    talkTo: 'تحدث مع MIWO...',
    voice: 'صوت',
    sportLabel: 'رياضة', sportTitle: 'كل مباراة.\nكل لحظة.',
    sportSub: 'نتائج مباشرة وتحليل معمّق وأبرز القصص. من ملاعب كرة القدم إلى حلبات السباق، من الفرق الصاعدة إلى الأساطير — الرياضة التي تُشكّل فهمنا للعالم.',
    sportPlaceholder: 'اسأل عن أي رياضة أو مباراة أو رياضي...',
    historyLabel: 'تاريخ', historyTitle: 'التاريخ ليس فقط\nما حدث.',
    historySub: 'إمبراطوريات قديمة ومماليك وسطى وثورات غيّرت كل شيء. والقصص التي نحكيها عن أسباب أهميتها. فهم الماضي هو السبيل الوحيد لفهم الحاضر.',
    historyPlaceholder: 'اسأل عن أي حقبة أو حدث أو شخصية...',
    classicsLabel: 'كلاسيكيات', classicsTitle: 'كل قديم\nجديد مرة أخرى.',
    classicsSub: 'روما واليونان القديمتان. فلسفة لا تزال تؤثر. أدب غيّر كل شيء. سياسة وأفكار فهمت كل شيء قبل آلاف السنين ولا نزال نحاول معرفة ما أرادت قوله.',
    classicsPlaceholder: 'اسأل عن روما أو اليونان أو الفلسفة أو أفلاطون أو أرسطو...',
    artsLabel: 'فنون وثقافة', artsTitle: 'الفن هو كيف\nنفهم الحاضر.',
    artsSub: 'فنون بصرية وموسيقى ومسرح وسينما — ما يجعلنا بشراً. من افتتاح المعارض إلى الحركات التي تهزّ العالم. لأن الثقافة هي المكان الذي يحدث فيه كل شيء حقاً.',
    artsPlaceholder: 'اسأل عن الفنون أو الموسيقى أو المسرح أو الثقافة...',
    natureLabel: 'طبيعة', natureTitle: 'الكوكب يتكلم.\nهل نسمع؟',
    natureSub: 'المناخ. المحيطات. الغابات. الطاقة. القصص البيئية التي تغيّر كل شيء. مروية بالعلم. بلا تزوير. بلا أمل زائف. فقط ما يحدث فعلاً.',
    naturePlaceholder: 'اسأل عن المناخ أو التنوع البيولوجي أو الطاقة أو الطبيعة...',
    cookLabel: 'طبخ', cookTitle: 'كل طبق\nله قصة.',
    cookSub: 'وصفات وتقنيات ومكونات — الثقافة والتاريخ والفرحة خلف ما نأكل. من وجبات سريعة خلال الأسبوع إلى تقاليد عريقة. لأن الطعام ليس مجرد طعام أبداً.',
    cookPlaceholder: 'اسأل عن أي وصفة أو تقنية أو مطبخ أو مكوّن...',
    pantryTitle: 'ماذا عندك في المطبخ؟',
    pantrySub: 'اكتب المكونات مفصولة بفواصل أو اضغط على الشرائح أدناه.',
    pantryAdd: '+ إضافة',
    pantryFind: 'ابحث عن وصفات',
    impressum: 'بيانات قانونية', legal: 'قانوني',
    allRights: 'جميع الحقوق محفوظة.',
    trademark: 'واسم وشعار MIWO هما علامتان تجاريتان لشركة Tindra Film GbR.',
    coFounder: 'مؤسس مشارك',
    miwoDesc: 'عالمي. خدمة إخبارية ذكية — مبنية لاختراق الضوضاء وتقديم العمق.',
    allSport: 'كل الرياضة', allArts: 'كل الفنون', allNature: 'كل الطبيعة',
    allHistory: 'كل التاريخ',
    you: 'أنت',
    stories: 'مقالات',
    askMiwo: 'اسأل MIWO',
    readMore: 'اقرأ المزيد',
    askMiwoAbout: 'اسأل MIWO عن هذا',
    whatDoYouHave: 'ماذا عندك؟',
    dailyFeature: 'زاوية اليوم',
    cowardsTitle: 'جبناء يجب أن نتذكرهم',
    cowardsSub: 'التاريخ مليء بالأبطال. ولكنه مليء أيضاً بمن عرفوا الصواب ولم يفعلوه.',
    backToBriefing: 'العودة إلى الملخص',
    errorMessage: 'حدث خطأ. حاول مرة أخرى.',
  },
};

const SUPPORTED_LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'de', label: 'DE', name: 'Deutsch' },
  { code: 'es', label: 'ES', name: 'Espa\u00F1ol' },
  { code: 'fr', label: 'FR', name: 'Fran\u00E7ais' },
  { code: 'ar', label: '\u0639\u0631', name: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629' },
];

const LangContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export function LangProvider({ children }) {
  const [lang, setLangState] = useState('en');

  useEffect(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('miwo-lang') : null;
    if (saved && translations[saved]) setLangState(saved);
  }, []);

  const RTL_LANGS = ['ar', 'he', 'fa', 'ur'];

  const setLang = (code) => {
    setLangState(code);
    if (typeof window !== 'undefined') localStorage.setItem('miwo-lang', code);
  };

  // Set dir and lang on <html> for RTL support
  useEffect(() => {
    if (typeof document === 'undefined') return;
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL_LANGS.includes(lang) ? 'rtl' : 'ltr';
  }, [lang]);

  const t = (key) => {
    return (translations[lang] && translations[lang][key]) || (translations.en && translations.en[key]) || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, SUPPORTED_LANGS }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export function LangPicker() {
  const { lang, setLang, SUPPORTED_LANGS } = useLang();

  return (
    <div className="lang-picker">
      {SUPPORTED_LANGS.map((l) => (
        <button
          key={l.code}
          className={`lang-btn ${lang === l.code ? 'active' : ''}`}
          onClick={() => setLang(l.code)}
          title={l.name}
        >
          {l.label}
        </button>
      ))}
    </div>
  );
}
