'use client';

import { createContext, useContext, useState, useEffect } from 'react';

// Translation keys for all UI text across the site
const translations = {
  en: {
    // Nav
    sport: 'Sport', history: 'History', arts: 'Arts', nature: 'Nature', cook: 'Cook', home: 'Home',
    // Main page
    tagline: 'The world in 30 seconds. News without the noise.',
    promise1: 'Only news, sourced and checked.',
    promise2: 'Ask. Follow up. Understand.',
    prompt1: 'What happened today?',
    prompt2: 'Catch me up',
    prompt3: 'Was ist heute in Deutschland passiert?',
    talkTo: 'Talk to MIWO...',
    voice: 'Voice',
    // Sport
    sportLabel: 'Sport', sportTitle: 'Every match\ntells a story.',
    sportSub: 'Live scores, deep analysis, and the stories behind the sport â from football pitches to Formula 1 circuits, across every continent.',
    sportPlaceholder: 'Ask about any sport, match, or athlete...',
    // History
    historyLabel: 'History', historyTitle: 'What happened\nbefore matters.',
    historySub: 'Ancient civilisations, medieval power, modern revolutions, and the myths we tell ourselves â explored with depth and honesty.',
    historyPlaceholder: 'Ask about any era, event, or figure...',
    // Arts
    artsLabel: 'Arts & Culture', artsTitle: 'The canvas of\ntoday\u2019s world.',
    artsSub: 'Visual arts, music, theatre, film and cultural news â curated and explained, from gallery openings to global movements.',
    artsPlaceholder: 'Ask about arts, music, theatre, culture...',
    // Nature
    natureLabel: 'Nature', natureTitle: 'The planet doesn\u2019t\nspin in silence.',
    natureSub: 'Climate, biodiversity, oceans, forests, energy â the environmental stories that shape everything, told with science and without greenwash.',
    naturePlaceholder: 'Ask about climate, biodiversity, energy, nature...',
    // Cook
    cookLabel: 'Cook', cookTitle: 'Every dish\nhas a story.',
    cookSub: 'Recipes, techniques, ingredients, and the culture behind what we eat â from quick weeknight meals to the deep traditions of world cuisine.',
    cookPlaceholder: 'Ask about any recipe, technique, cuisine, or ingredient...',
    pantryTitle: 'What\u2019s in your kitchen?',
    pantrySub: 'Type your ingredients separated by commas, or tap the chips below. We\u2019ll suggest what you can cook right now.',
    pantryAdd: '+ Add',
    pantryFind: 'Find Recipes',
    // Impressum
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'All rights reserved.',
    trademark: 'and the MIWO name and logo are trademarks of Tindra Film GbR. Content generated by MIWO is for informational purposes only and does not constitute professional advice. All editorial output is AI-assisted and should be independently verified.',
    coFounder: 'Co-Founder',
    miwoDesc: 'My World. A daily news check-in for people who gave up on the news. Fast, honest, global.',
    // Filters
    allSport: 'All Sport', allArts: 'All Arts', allNature: 'All Nature',
    allHistory: 'All History',
    // Common
    you: 'You',
    stories: 'Stories',
    askMiwo: 'Ask MIWO',
    readMore: 'Read more',
    askMiwoAbout: 'Ask MIWO about this',
    whatDoYouHave: 'What do you have?',
    dailyFeature: 'Daily Feature',
    cowardsTitle: 'Cowards We Should Remember',
    cowardsSub: 'History is full of heroes. It\u2019s also full of people who knew what was right, had the power to act, and chose not to. Today\u2019s story',
    backToBriefing: 'Back to briefing',
    errorMessage: 'Something went wrong. Try again in a moment.',
  },
  de: {
    sport: 'Sport', history: 'Geschichte', arts: 'Kunst', nature: 'Natur', cook: 'Kochen', home: 'Start',
    tagline: 'Die Welt in 30 Sekunden. Nachrichten ohne L\u00E4rm.',
    promise1: 'Nur Nachrichten, recherchiert und gepr\u00FCft.',
    promise2: 'Fragen. Nachhaken. Verstehen.',
    prompt1: 'Was ist heute passiert?',
    prompt2: 'Bring mich auf den Stand',
    prompt3: 'What happened in the UK today?',
    talkTo: 'Sprich mit MIWO...',
    voice: 'Stimme',
    sportLabel: 'Sport', sportTitle: 'Jedes Spiel\nerz\u00E4hlt eine Geschichte.',
    sportSub: 'Live-Ergebnisse, tiefgehende Analysen und die Geschichten hinter dem Sport \u2014 von Fu\u00DFballpl\u00E4tzen bis zu Formel-1-Strecken, auf jedem Kontinent.',
    sportPlaceholder: 'Frag nach Sport, Spielen oder Athleten...',
    historyLabel: 'Geschichte', historyTitle: 'Was vorher\ngeschah, z\u00E4hlt.',
    historySub: 'Antike Zivilisationen, mittelalterliche Macht, moderne Revolutionen und die Mythen, die wir uns erz\u00E4hlen \u2014 erforscht mit Tiefe und Ehrlichkeit.',
    historyPlaceholder: 'Frag nach einer Epoche, einem Ereignis oder einer Person...',
    artsLabel: 'Kunst & Kultur', artsTitle: 'Die Leinwand\nder heutigen Welt.',
    artsSub: 'Bildende Kunst, Musik, Theater, Film und Kulturnachrichten \u2014 kuratiert und erkl\u00E4rt.',
    artsPlaceholder: 'Frag nach Kunst, Musik, Theater, Kultur...',
    natureLabel: 'Natur', natureTitle: 'Der Planet dreht\nsich nicht in Stille.',
    natureSub: 'Klima, Biodiversit\u00E4t, Ozeane, W\u00E4lder, Energie \u2014 die Umweltgeschichten, die alles pr\u00E4gen, erz\u00E4hlt mit Wissenschaft und ohne Greenwashing.',
    naturePlaceholder: 'Frag nach Klima, Biodiversit\u00E4t, Energie, Natur...',
    cookLabel: 'Kochen', cookTitle: 'Jedes Gericht\nhat eine Geschichte.',
    cookSub: 'Rezepte, Techniken, Zutaten und die Kultur hinter dem, was wir essen.',
    cookPlaceholder: 'Frag nach Rezepten, Techniken, K\u00FCche oder Zutaten...',
    pantryTitle: 'Was hast du in der K\u00FCche?',
    pantrySub: 'Gib deine Zutaten durch Kommas getrennt ein oder tippe auf die Chips unten.',
    pantryAdd: '+ Hinzuf\u00FCgen',
    pantryFind: 'Rezepte finden',
    impressum: 'Impressum', legal: 'Rechtliches',
    allRights: 'Alle Rechte vorbehalten.',
    trademark: 'und der MIWO-Name und das Logo sind Marken der Tindra Film GbR. Von MIWO generierte Inhalte dienen nur zu Informationszwecken.',
    coFounder: 'Mitgr\u00FCnder/in',
    miwoDesc: 'Meine Welt. Ein konversationeller Nachrichtenintelligenz-Dienst \u2014 gebaut, um durch LÃ¤rm zu schneiden, Desinformation zu bek\u00E4mpfen und Tiefe zu liefern.',
    allSport: 'Alle Sportarten', allArts: 'Alle Kunst', allNature: 'Alle Natur',
    allHistory: 'Alle Geschichte',
    you: 'Du',
    stories: 'Beitr\u00E4ge',
    askMiwo: 'Frag MIWO',
    readMore: 'Weiterlesen',
    askMiwoAbout: 'MIWO dazu fragen',
    whatDoYouHave: 'Was hast du da?',
    dailyFeature: 'Tagesrubrik',
    cowardsTitle: 'Feiglinge, an die wir uns erinnern sollten',
    cowardsSub: 'Die Geschichte ist voller Helden. Sie ist auch voller Menschen, die wussten, was richtig war, die Macht hatten zu handeln, und es nicht taten.',
    backToBriefing: 'Zur\u00FCck zum Briefing',
    errorMessage: 'Etwas ist schiefgelaufen. Versuche es gleich nochmal.',
  },
  es: {
    sport: 'Deporte', history: 'Historia', arts: 'Arte', nature: 'Naturaleza', cook: 'Cocina', home: 'Inicio',
    tagline: 'El mundo en 30 segundos. Noticias sin ruido.',
    promise1: 'Solo noticias, verificadas y contrastadas.',
    promise2: 'Pregunta. Profundiza. Comprende.',
    prompt1: '\u00BFQu\u00E9 pas\u00F3 hoy?',
    prompt2: 'Ponme al d\u00EDa',
    prompt3: '\u00BFQu\u00E9 pas\u00F3 hoy en Am\u00E9rica Latina?',
    talkTo: 'Habla con MIWO...',
    voice: 'Voz',
    sportLabel: 'Deporte', sportTitle: 'Cada partido\ncuenta una historia.',
    sportSub: 'Resultados en vivo, an\u00E1lisis profundo y las historias detr\u00E1s del deporte.',
    sportPlaceholder: 'Pregunta sobre deportes, partidos o atletas...',
    historyLabel: 'Historia', historyTitle: 'Lo que pas\u00F3\nantes importa.',
    historySub: 'Civilizaciones antiguas, poder medieval, revoluciones modernas y los mitos que nos contamos.',
    historyPlaceholder: 'Pregunta sobre cualquier \u00E9poca, evento o figura...',
    artsLabel: 'Arte y Cultura', artsTitle: 'El lienzo del\nmundo actual.',
    artsSub: 'Artes visuales, m\u00FAsica, teatro, cine y noticias culturales.',
    artsPlaceholder: 'Pregunta sobre arte, m\u00FAsica, teatro, cultura...',
    natureLabel: 'Naturaleza', natureTitle: 'El planeta no\ngira en silencio.',
    natureSub: 'Clima, biodiversidad, oc\u00E9anos, bosques, energ\u00EDa \u2014 contado con ciencia y sin greenwashing.',
    naturePlaceholder: 'Pregunta sobre clima, biodiversidad, energ\u00EDa...',
    cookLabel: 'Cocina', cookTitle: 'Cada plato\ntiene una historia.',
    cookSub: 'Recetas, t\u00E9cnicas, ingredientes y la cultura detr\u00E1s de lo que comemos.',
    cookPlaceholder: 'Pregunta sobre recetas, t\u00E9cnicas, cocina o ingredientes...',
    pantryTitle: '\u00BFQu\u00E9 tienes en la cocina?',
    pantrySub: 'Escribe tus ingredientes separados por comas o toca las etiquetas.',
    pantryAdd: '+ A\u00F1adir',
    pantryFind: 'Buscar recetas',
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'Todos los derechos reservados.',
    trademark: 'y el nombre y logotipo de MIWO son marcas registradas de Tindra Film GbR.',
    coFounder: 'Cofundador/a',
    miwoDesc: 'Mi Mundo. Un servicio de inteligencia de noticias conversacional.',
    allSport: 'Todo Deporte', allArts: 'Todo Arte', allNature: 'Toda Naturaleza',
    allHistory: 'Toda Historia',
    you: 'T\u00FA',
    stories: 'Historias',
    askMiwo: 'Pregunta a MIWO',
    readMore: 'Leer m\u00E1s',
    askMiwoAbout: 'Preguntar a MIWO sobre esto',
    whatDoYouHave: '\u00BFQu\u00E9 tienes?',
    dailyFeature: 'Secci\u00F3n del d\u00EDa',
    cowardsTitle: 'Cobardes que debemos recordar',
    cowardsSub: 'La historia est\u00E1 llena de h\u00E9roes. Tambi\u00E9n est\u00E1 llena de personas que sab\u00EDan lo correcto, ten\u00EDan el poder de actuar, y eligieron no hacerlo.',
    backToBriefing: 'Volver al briefing',
    errorMessage: 'Algo sali\u00F3 mal. Int\u00E9ntalo de nuevo en un momento.',
  },
  fr: {
    sport: 'Sport', history: 'Histoire', arts: 'Arts', nature: 'Nature', cook: 'Cuisine', home: 'Accueil',
    tagline: 'Le monde en 30 secondes. L\u2019info sans le bruit.',
    promise1: 'Rien que l\u2019info, v\u00E9rifi\u00E9e et sourc\u00E9e.',
    promise2: 'Demandez. Creusez. Comprenez.',
    prompt1: 'Que s\u2019est-il pass\u00E9 aujourd\u2019hui\u00A0?',
    prompt2: 'Mets-moi \u00E0 jour',
    prompt3: 'Quoi de neuf en Afrique francophone\u00A0?',
    talkTo: 'Parlez \u00E0 MIWO...',
    voice: 'Voix',
    sportLabel: 'Sport', sportTitle: 'Chaque match\nraconte une histoire.',
    sportSub: 'R\u00E9sultats en direct, analyses et les histoires derri\u00E8re le sport.',
    sportPlaceholder: 'Posez une question sur le sport, un match ou un athl\u00E8te...',
    historyLabel: 'Histoire', historyTitle: 'Ce qui s\u2019est pass\u00E9\navant compte.',
    historySub: 'Civilisations antiques, pouvoir m\u00E9di\u00E9val, r\u00E9volutions modernes et les mythes que nous racontons.',
    historyPlaceholder: 'Posez une question sur une \u00E9poque, un \u00E9v\u00E9nement ou un personnage...',
    artsLabel: 'Arts et Culture', artsTitle: 'La toile du\nmonde d\u2019aujourd\u2019hui.',
    artsSub: 'Arts visuels, musique, th\u00E9\u00E2tre, cin\u00E9ma et actualit\u00E9s culturelles.',
    artsPlaceholder: 'Posez une question sur les arts, la musique, le th\u00E9\u00E2tre...',
    natureLabel: 'Nature', natureTitle: 'La plan\u00E8te ne\ntourne pas en silence.',
    natureSub: 'Climat, biodiversit\u00E9, oc\u00E9ans, for\u00EAts, \u00E9nergie \u2014 racont\u00E9 avec science et sans greenwashing.',
    naturePlaceholder: 'Posez une question sur le climat, la biodiversit\u00E9, l\u2019\u00E9nergie...',
    cookLabel: 'Cuisine', cookTitle: 'Chaque plat\na une histoire.',
    cookSub: 'Recettes, techniques, ingr\u00E9dients et la culture derri\u00E8re ce que nous mangeons.',
    cookPlaceholder: 'Posez une question sur les recettes, techniques, cuisine...',
    pantryTitle: 'Qu\u2019avez-vous dans la cuisine\u00A0?',
    pantrySub: 'Tapez vos ingr\u00E9dients s\u00E9par\u00E9s par des virgules ou touchez les puces.',
    pantryAdd: '+ Ajouter',
    pantryFind: 'Trouver des recettes',
    impressum: 'Mentions l\u00E9gales', legal: 'L\u00E9gal',
    allRights: 'Tous droits r\u00E9serv\u00E9s.',
    trademark: 'et le nom et logo MIWO sont des marques de Tindra Film GbR.',
    coFounder: 'Cofondateur/trice',
    miwoDesc: 'Mon Monde. Un service d\u2019intelligence m\u00E9diatique conversationnel.',
    allSport: 'Tous les Sports', allArts: 'Tous les Arts', allNature: 'Toute la Nature',
    allHistory: 'Toute l\u2019Histoire',
    you: 'Vous',
    stories: 'Articles',
    askMiwo: 'Demander \u00E0 MIWO',
    readMore: 'Lire la suite',
    askMiwoAbout: 'Demander \u00E0 MIWO',
    whatDoYouHave: 'Qu\u2019avez-vous\u00A0?',
    dailyFeature: 'Rubrique du jour',
    cowardsTitle: 'L\u00E2ches dont il faut se souvenir',
    cowardsSub: 'L\u2019histoire est pleine de h\u00E9ros. Elle est aussi pleine de gens qui savaient ce qui \u00E9tait juste, avaient le pouvoir d\u2019agir, et ont choisi de ne pas le faire.',
    backToBriefing: 'Retour au briefing',
    errorMessage: 'Quelque chose s\u2019est mal pass\u00E9. R\u00E9essayez dans un instant.',
  },
  ar: {
    sport: '\u0631\u064A\u0627\u0636\u0629', history: '\u062A\u0627\u0631\u064A\u062E', arts: '\u0641\u0646\u0648\u0646', nature: '\u0637\u0628\u064A\u0639\u0629', cook: '\u0637\u0628\u062E', home: '\u0627\u0644\u0631\u0626\u064A\u0633\u064A\u0629',
    tagline: '\u0645\u062D\u0631\u0631\u0643 \u0627\u0644\u0625\u062E\u0628\u0627\u0631\u064A \u0627\u0644\u0645\u0648\u062B\u0648\u0642. \u0627\u0633\u0623\u0644\u0646\u064A \u0645\u0627\u0630\u0627 \u062D\u062F\u062B \u0627\u0644\u064A\u0648\u0645.',
    promise1: '\u0623\u062E\u0628\u0627\u0631 \u0641\u0642\u0637\u060C \u0645\u0648\u062B\u0642\u0629 \u0648\u0645\u0648\u062B\u0648\u0642\u0629.',
    promise2: '\u0627\u0633\u0623\u0644. \u062A\u0627\u0628\u0639. \u0627\u0641\u0647\u0645.',
    prompt1: '\u0645\u0627\u0630\u0627 \u062D\u062F\u062B \u0627\u0644\u064A\u0648\u0645\u061F',
    prompt2: '\u0623\u0639\u0637\u0646\u064A \u0627\u0644\u0645\u0644\u062E\u0635 \u0627\u0644\u0639\u0627\u0644\u0645\u064A',
    prompt3: '\u0645\u0627 \u0627\u0644\u062C\u062F\u064A\u062F \u0641\u064A \u0627\u0644\u0634\u0631\u0642 \u0627\u0644\u0623\u0648\u0633\u0637\u061F',
    talkTo: '\u062A\u062D\u062F\u062B \u0645\u0639 MIWO...',
    voice: '\u0635\u0648\u062A',
    sportLabel: '\u0631\u064A\u0627\u0636\u0629', sportTitle: '\u0643\u0644 \u0645\u0628\u0627\u0631\u0627\u0629\n\u062A\u0631\u0648\u064A \u0642\u0635\u0629.',
    sportSub: '\u0646\u062A\u0627\u0626\u062C \u0645\u0628\u0627\u0634\u0631\u0629 \u0648\u062A\u062D\u0644\u064A\u0644 \u0639\u0645\u064A\u0642.',
    sportPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0631\u064A\u0627\u0636\u0629...',
    historyLabel: '\u062A\u0627\u0631\u064A\u062E', historyTitle: '\u0645\u0627 \u062D\u062F\u062B\n\u0642\u0628\u0644\u0627\u064B \u0645\u0647\u0645.',
    historySub: '\u062D\u0636\u0627\u0631\u0627\u062A \u0642\u062F\u064A\u0645\u0629 \u0648\u062B\u0648\u0631\u0627\u062A \u062D\u062F\u064A\u062B\u0629.',
    historyPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0623\u064A \u062D\u0642\u0628\u0629 \u0623\u0648 \u062D\u062F\u062B...',
    artsLabel: '\u0641\u0646\u0648\u0646 \u0648\u062B\u0642\u0627\u0641\u0629', artsTitle: '\u0644\u0648\u062D\u0629\n\u0627\u0644\u0639\u0627\u0644\u0645 \u0627\u0644\u064A\u0648\u0645.',
    artsSub: '\u0641\u0646\u0648\u0646 \u0628\u0635\u0631\u064A\u0629 \u0648\u0645\u0648\u0633\u064A\u0642\u0649 \u0648\u0645\u0633\u0631\u062D \u0648\u0633\u064A\u0646\u0645\u0627.',
    artsPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0641\u0646\u0648\u0646...',
    natureLabel: '\u0637\u0628\u064A\u0639\u0629', natureTitle: '\u0627\u0644\u0643\u0648\u0643\u0628 \u0644\u0627\n\u064A\u062F\u0648\u0631 \u0628\u0635\u0645\u062E.',
    natureSub: '\u0627\u0644\u0645\u0646\u0627\u062E \u0648\u0627\u0644\u062A\u0646\u0648\u0639 \u0627\u0644\u0628\u064A\u0648\u0644\u0648\u062C\u064A \u0648\u0627\u0644\u0637\u0627\u0642\u0629.',
    naturePlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0645\u0646\u0627\u062E \u0648\u0627\u0644\u0637\u0628\u064A\u0639\u0629...',
    cookLabel: '\u0637\u0628\u062E', cookTitle: '\u0643\u0644 \u0637\u0628\u0642\n\u0644\u0647 \u0642\u0635\u0629.',
    cookSub: '\u0648\u0635\u0641\u0627\u062A \u0648\u062A\u0642\u0646\u064A\u0627\u062A \u0648\u0645\u0643\u0648\u0646\u0627\u062A.',
    cookPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0648\u0635\u0641\u0627\u062A...',
    pantryTitle: '\u0645\u0627\u0630\u0627 \u0639\u0646\u062F\u0643 \u0641\u064A \u0627\u0644\u0645\u0637\u0628\u062E\u061F',
    pantrySub: '\u0627\u0643\u062A\u0628 \u0627\u0644\u0645\u0643\u0648\u0646\u0627\u062A.',
    pantryAdd: '+ \u0625\u0636\u0627\u0641\u0629',
    pantryFind: '\u0627\u0628\u062D\u062B \u0639\u0646 \u0648\u0635\u0641\u0627\u062A',
    impressum: '\u0628\u064A\u0627\u0646\u0627\u062A \u0642\u0627\u0646\u0648\u0646\u064A\u0629', legal: '\u0642\u0627\u0646\u0648\u0646\u064A',
    allRights: '\u062C\u0645\u064A\u0639 \u0627\u0644\u062D\u0642\u0648\u0642 \u0645\u062D\u0641\u0648\u0638\u0629.',
    trademark: '',
    coFounder: '\u0645\u0624\u0633\u0633 \u0645\u0634\u0627\u0631\u0643',
    miwoDesc: '\u0639\u0627\u0644\u0645\u064A. \u062E\u062F\u0645\u0629 \u0625\u062E\u0628\u0627\u0631\u064A\u0629 \u0630\u0643\u064A\u0629.',
    allSport: '\u0643\u0644 \u0627\u0644\u0631\u064A\u0627\u0636\u0629', allArts: '\u0643\u0644 \u0627\u0644\u0641\u0646\u0648\u0646', allNature: '\u0643\u0644 \u0627\u0644\u0637\u0628\u064A\u0639\u0629',
    allHistory: '\u0643\u0644 \u0627\u0644\u062A\u0627\u0631\u064A\u062E',
    you: '\u0623\u0646\u062E',
    stories: '\u0645\u0642\u0627\u0644\u0627\u062B',
    askMiwo: '\u0627\u0633\u0623\u0644 MIWO',
    readMore: '\u0627\u0642\u0631\u0623 \u0627\u0644\u0645\u0632\u064A\u062F',
    askMiwoAbout: '\u0627\u0633\u0623\u0644 MIWO \u0639\u0646 \u0647\u0630\u0627',
    whatDoYouHave: '\u0645\u0627\u0630\u0627 \u0639\u0646\u062F\u0643\u061F',
    dailyFeature: '\u0632\u0627\u0648\u064A\u0629 \u0627\u0644\u064A\u0648\u0645',
    cowardsTitle: '\u062C\u0628\u0646\u0627\u0621 \u064A\u062C\u0628 \u0623\u0646 \u0646\u062A\u0630\u0643\u0631\u0647\u0645',
    cowardsSub: '\u0627\u0644\u062A\u0627\u0631\u064A\u062E \u0645\u0644\u064A\u0621 \u0628\u0627\u0644\u0623\u0628\u0637\u0627\u0644. \u0648\u0644\u0643\u0646\u0647 \u0645\u0644\u064A\u0621 \u0623\u064A\u0636\u0627\u064B \u0628\u0645\u0646 \u0639\u0631\u0641\u0648\u0627 \u0627\u0644\u0635\u0648\u0627\u0628 \u0648\u0644\u0645 \u064A\u0641\u0639\u0644\u0648\u0627.',
    backToBriefing: '\u0627\u0644\u0639\u0648\u062F\u0629 \u0625\u0644\u0649 \u0627\u0644\u0645\u0644\u062E\u0635',
    errorMessage: '\u062D\u062F\u062B \u062E\u0637\u0623. \u062D\u0627\u0648\u0644 \u0645\u0631\u0629 \u0623\u062E\u0631\u0649.',
  },
};

const SUPPORTED_LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'de', label: 'DE', name: 'Deutsch' },
  { code: 'es', label: 'ES', name: 'Espa\u00F1ol' },
  { code: 'fr', label: 'FR', name: 'Fran\u00E7ais' },
  { code: 'ar', label: '\u0639\u0631', name: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629' },
];

const LangContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export function LangProvider({ children }) {
  const [lang, setLangState] = useState('en');

  useEffect(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('miwo-lang') : null;
    if (saved && translations[saved]) setLangState(saved);
  }, []);

  const setLang = (code) => {
    setLangState(code);
    if (typeof window !== 'undefined') localStorage.setItem('miwo-lang', code);
  };

  const t = (key) => {
    return (translations[lang] && translations[lang][key]) || (translations.en && translations.en[key]) || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, SUPPORTED_LANGS }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export function LangPicker() {
  const { lang, setLang, SUPPORTED_LANGS } = useLang();

  return (
    <div className="lang-picker">
      {SUPPORTED_LANGS.map((l) => (
        <button
          key={l.code}
          className={`lang-btn ${lang === l.code ? 'active' : ''}`}
          onClick={() => setLang(l.code)}
          title={l.name}
        >
          {l.label}
        </button>
      ))}
    </div>
  );
}
