'use client';

import { createContext, useContext, useState, useEffect } from 'react';

// Translation keys for all UI text across the site
const translations = {
  en: {
    // Nav
    sport: 'Sport', history: 'History', arts: 'Arts', classics: 'Classics', nature: 'Nature', cook: 'Cook', home: 'Home',
    // Main page
    tagline: 'The world in 30 seconds. News without the noise.',
    promise1: 'Only news, sourced and checked.',
    promise2: 'Ask. Follow up. Understand.',
    prompt1: 'What happened today?',
    prompt2: 'Catch me up',
    prompt3: 'Was ist heute in Deutschland passiert?',
    talkTo: 'Talk to MIWO...',
    voice: 'Voice',
    // Sport
    sportLabel: 'Sport', sportTitle: 'Every match.\nEvery moment.',
    sportSub: 'Live scores, deep analysis, and the stories that matter. From football pitches to racing circuits, from underdogs to dynasties — the sport that shapes how we understand the world.',
    sportPlaceholder: 'Ask about any sport, match, or athlete...',
    // History
    historyLabel: 'History', historyTitle: 'History isn\'t just\nwhat happened.',
    historySub: 'Ancient empires, medieval kingdoms, revolutions that shook everything. And the stories we tell ourselves about why it mattered. Understanding the past is the only way to understand now.',
    historyPlaceholder: 'Ask about any era, event, or figure...',
    // Classics
    classicsLabel: 'Classics', classicsTitle: 'Everything old\nis new again.',
    classicsSub: 'Ancient Rome and Greece. Philosophy that still hits. Literature that changed everything. Politics, culture, ideas that somehow got everything right thousands of years ago and we\'re still figuring out what they meant.',
    classicsPlaceholder: 'Ask about Rome, Greece, philosophy, Plato, Aristotle, Stoicism...',
    // Arts
    artsLabel: 'Arts & Culture', artsTitle: 'Art is how we\nunderstand now.',
    artsSub: 'Visual arts, music, theatre, film — the stuff that makes us human. From gallery openings to movements that shake the world. Because culture is where everything real happens.',
    artsPlaceholder: 'Ask about arts, music, theatre, culture...',
    // Nature
    natureLabel: 'Nature', natureTitle: 'The planet speaks.\nAre we listening?',
    natureSub: 'Climate. Oceans. Forests. Energy. The environmental stories that change everything. Told with science. No greenwash. No false hope. Just what\'s really happening.',
    naturePlaceholder: 'Ask about climate, biodiversity, energy, nature...',
    // Cook
    cookLabel: 'Cook', cookTitle: 'Every meal tells\na story.',
    cookSub: 'Recipes, techniques, ingredients — the culture, history, and joy behind what we eat. From weeknight quick fixes to centuries of tradition. Because food is never just food.',
    cookPlaceholder: 'Ask about any recipe, technique, cuisine, or ingredient...',
    pantryTitle: 'What\u2019s in your kitchen?',
    pantrySub: 'Type your ingredients separated by commas, or tap the chips below. We\u2019ll suggest what you can cook right now.',
    pantryAdd: '+ Add',
    pantryFind: 'Find Recipes',
    // Impressum
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'All rights reserved.',
    trademark: 'and the MIWO name and logo are trademarks of Tindra Film GbR. Content generated by MIWO is for informational purposes only and does not constitute professional advice. All editorial output is AI-assisted and should be independently verified.',
    coFounder: 'Co-Founder',
    miwoDesc: 'My World. A daily news check-in for people who gave up on the news. Fast, honest, global.',
    // Filters
    allSport: 'All Sport', allArts: 'All Arts', allNature: 'All Nature',
    allHistory: 'All History',
    // Common
    you: 'You',
    stories: 'Stories',
    askMiwo: 'Ask MIWO',
    readMore: 'Read more',
    askMiwoAbout: 'Ask MIWO about this',
    whatDoYouHave: 'What do you have?',
    dailyFeature: 'Daily Feature',
    cowardsTitle: 'Cowards We Should Remember',
    cowardsSub: 'History is full of heroes. It\u2019s also full of people who knew what was right, had the power to act, and chose not to. Today\u2019s story',
    backToBriefing: 'Back to briefing',
    errorMessage: 'Something went wrong. Try again in a moment.',
  },
  de: {
    sport: 'Sport', history: 'Geschichte', arts: 'Kunst', classics: 'Klassik', nature: 'Natur', cook: 'Kochen', home: 'Start',
    tagline: 'Die Welt in 30 Sekunden. Nachrichten ohne L\u00E4rm.',
    promise1: 'Nur Nachrichten, recherchiert und gepr\u00FCft.',
    promise2: 'Fragen. Nachhaken. Verstehen.',
    prompt1: 'Was ist heute passiert?',
    prompt2: 'Bring mich auf den Stand',
    prompt3: 'What happened in the UK today?',
    talkTo: 'Sprich mit MIWO...',
    voice: 'Stimme',
    sportLabel: 'Sport', sportTitle: 'Jedes Spiel.\nJeder Moment.',
    sportSub: 'Live-Ergebnisse, tiefe Analysen und die Geschichten, die zählen. Von Fußballplätzen bis zu Rennstrecken, von Außenseitern bis zu Dynastien — der Sport, der zeigt, wie wir die Welt verstehen.',
    sportPlaceholder: 'Frag nach Sport, Spielen oder Athleten...',
    historyLabel: 'Geschichte', historyTitle: 'Geschichte ist nicht nur\nwas geschah.',
    historySub: 'Antike Imperien, mittelalterliche Königreiche, Revolutionen, die alles verändert haben. Und die Geschichten, die wir uns über die Bedeutung erzählen. Die Vergangenheit verstehen ist der einzige Weg, um jetzt zu verstehen.',
    historyPlaceholder: 'Frag nach einer Epoche, einem Ereignis oder einer Person...',
    classicsLabel: 'Klassik', classicsTitle: 'Alles Alte\nist neu.',
    classicsSub: 'Antikes Rom und Griechenland. Philosophie, die immer noch wirkt. Literatur, die alles ver\u00E4ndert hat. Politik und Ideen, die vor Tausenden von Jahren alles richtig verstanden haben und wir versuchen immer noch, sie zu begreifen.',
    classicsPlaceholder: 'Frag nach Rom, Griechenland, Philosophie, Platon, Aristoteles, Stoizismus...',
    artsLabel: 'Kunst & Kultur', artsTitle: 'Kunst ist wie wir\njetzt verstehen.',
    artsSub: 'Bildende Kunst, Musik, Theater, Film — das Zeug, das uns menschlich macht. Von Galerieöffnungen bis zu Bewegungen, die die Welt erschüttern. Denn Kultur ist dort, wo wirklich alles passiert.',
    artsPlaceholder: 'Frag nach Kunst, Musik, Theater, Kultur...',
    natureLabel: 'Natur', natureTitle: 'Der Planet spricht.\nH\u00F6ren wir zu?',
    natureSub: 'Klima. Ozeane. W\u00E4lder. Energie. Die Umweltgeschichten, die alles verändern. Erzählt mit Wissenschaft. Ohne Greenwashing. Ohne falsche Hoffnung. Nur das, was wirklich passiert.',
    naturePlaceholder: 'Frag nach Klima, Biodiversit\u00E4t, Energie, Natur...',
    cookLabel: 'Kochen', cookTitle: 'Jedes Essen erzählt\neine Geschichte.',
    cookSub: 'Rezepte, Techniken, Zutaten — die Kultur, Geschichte und Freude hinter dem, was wir essen. Von schnellen Wochentags-Mahlzeiten bis zu jahrhundertealten Traditionen. Denn Essen ist nie nur Essen.',
    cookPlaceholder: 'Frag nach Rezepten, Techniken, K\u00FCche oder Zutaten...',
    pantryTitle: 'Was hast du in der K\u00FCche?',
    pantrySub: 'Gib deine Zutaten durch Kommas getrennt ein oder tippe auf die Chips unten.',
    pantryAdd: '+ Hinzuf\u00FCgen',
    pantryFind: 'Rezepte finden',
    impressum: 'Impressum', legal: 'Rechtliches',
    allRights: 'Alle Rechte vorbehalten.',
    trademark: 'und der MIWO-Name und das Logo sind Marken der Tindra Film GbR. Von MIWO generierte Inhalte dienen nur zu Informationszwecken.',
    coFounder: 'Mitgr\u00FCnder/in',
    miwoDesc: 'Meine Welt. Ein konversationeller Nachrichtenintelligenz-Dienst \u2014 gebaut, um durch Lärm zu schneiden, Desinformation zu bek\u00E4mpfen und Tiefe zu liefern.',
    allSport: 'Alle Sportarten', allArts: 'Alle Kunst', allNature: 'Alle Natur',
    allHistory: 'Alle Geschichte',
    you: 'Du',
    stories: 'Beitr\u00E4ge',
    askMiwo: 'Frag MIWO',
    readMore: 'Weiterlesen',
    askMiwoAbout: 'MIWO dazu fragen',
    whatDoYouHave: 'Was hast du da?',
    dailyFeature: 'Tagesrubrik',
    cowardsTitle: 'Feiglinge, an die wir uns erinnern sollten',
    cowardsSub: 'Die Geschichte ist voller Helden. Sie ist auch voller Menschen, die wussten, was richtig war, die Macht hatten zu handeln, und es nicht taten.',
    backToBriefing: 'Zur\u00FCck zum Briefing',
    errorMessage: 'Etwas ist schiefgelaufen. Versuche es gleich nochmal.',
  },
  es: {
    sport: 'Deporte', history: 'Historia', arts: 'Arte', classics: 'Cl\u00E1sicos', nature: 'Naturaleza', cook: 'Cocina', home: 'Inicio',
    tagline: 'El mundo en 30 segundos. Noticias sin ruido.',
    promise1: 'Solo noticias, verificadas y contrastadas.',
    promise2: 'Pregunta. Profundiza. Comprende.',
    prompt1: '\u00BFQu\u00E9 pas\u00F3 hoy?',
    prompt2: 'Ponme al d\u00EDa',
    prompt3: '\u00BFQu\u00E9 pas\u00F3 hoy en Am\u00E9rica Latina?',
    talkTo: 'Habla con MIWO...',
    voice: 'Voz',
    sportLabel: 'Deporte', sportTitle: 'Cada partido.\nCada momento.',
    sportSub: 'Resultados en vivo, análisis profundo y las historias que importan. De los campos de fútbol a las pistas de carreras. Porque el deporte es cómo entendemos el mundo.',
    sportPlaceholder: 'Pregunta sobre deportes, partidos o atletas...',
    historyLabel: 'Historia', historyTitle: 'La historia no es solo\nqué pasó.',
    historySub: 'Imperios antiguos, reinos medievales, revoluciones que lo cambiaron todo. Y las historias que nos contamos sobre por qué importó. Entender el pasado es la única forma de entender ahora.',
    historyPlaceholder: 'Pregunta sobre cualquier \u00E9poca, evento o figura...',
    classicsLabel: 'Cl\u00E1sicos', classicsTitle: 'Todo lo antiguo\nes nuevo otra vez.',
    classicsSub: 'Roma y Grecia antiguas. Filosof\u00EDa que a\u00FAn resuena. Literatura que lo cambi\u00F3 todo. Ideas de hace miles de a\u00F1os que de alguna manera acertaron en todo, y a\u00FAn estamos intentando entender qu\u00E9 quisieron decir.',
    classicsPlaceholder: 'Pregunta sobre Roma, Grecia, filosof\u00EDa, Plat\u00F3n, Arist\u00F3teles...',
    artsLabel: 'Arte y Cultura', artsTitle: 'El arte es cómo\nentendemos ahora.',
    artsSub: 'Artes visuales, música, teatro, cine — lo que nos hace humanos. De galerías a movimientos que sacuden el mundo. Porque la cultura es donde realmente sucede todo.',
    artsPlaceholder: 'Pregunta sobre arte, m\u00FAsica, teatro, cultura...',
    natureLabel: 'Naturaleza', natureTitle: 'El planeta habla.\n¿Estamos escuchando?',
    natureSub: 'Clima. Océanos. Bosques. Energía. Las historias ambientales que lo cambian todo. Contadas con ciencia. Sin greenwashing. Sin falsas esperanzas. Solo lo que está pasando realmente.',
    naturePlaceholder: 'Pregunta sobre clima, biodiversidad, energ\u00EDa...',
    cookLabel: 'Cocina', cookTitle: 'Cada comida cuenta\nuna historia.',
    cookSub: 'Recetas, técnicas, ingredientes — la cultura, historia y alegría detrás de lo que comemos. Desde comidas rápidas de la semana hasta tradiciones centenarias. Porque la comida nunca es solo comida.',
    cookPlaceholder: 'Pregunta sobre recetas, t\u00E9cnicas, cocina o ingredientes...',
    pantryTitle: '\u00BFQu\u00E9 tienes en la cocina?',
    pantrySub: 'Escribe tus ingredientes separados por comas o toca las etiquetas.',
    pantryAdd: '+ A\u00F1adir',
    pantryFind: 'Buscar recetas',
    impressum: 'Impressum', legal: 'Legal',
    allRights: 'Todos los derechos reservados.',
    trademark: 'y el nombre y logotipo de MIWO son marcas registradas de Tindra Film GbR.',
    coFounder: 'Cofundador/a',
    miwoDesc: 'Mi Mundo. Un servicio de inteligencia de noticias conversacional.',
    allSport: 'Todo Deporte', allArts: 'Todo Arte', allNature: 'Toda Naturaleza',
    allHistory: 'Toda Historia',
    you: 'T\u00FA',
    stories: 'Historias',
    askMiwo: 'Pregunta a MIWO',
    readMore: 'Leer m\u00E1s',
    askMiwoAbout: 'Preguntar a MIWO sobre esto',
    whatDoYouHave: '\u00BFQu\u00E9 tienes?',
    dailyFeature: 'Secci\u00F3n del d\u00EDa',
    cowardsTitle: 'Cobardes que debemos recordar',
    cowardsSub: 'La historia est\u00E1 llena de h\u00E9roes. Tambi\u00E9n est\u00E1 llena de personas que sab\u00EDan lo correcto, ten\u00EDan el poder de actuar, y eligieron no hacerlo.',
    backToBriefing: 'Volver al briefing',
    errorMessage: 'Algo sali\u00F3 mal. Int\u00E9ntalo de nuevo en un momento.',
  },
  fr: {
    sport: 'Sport', history: 'Histoire', arts: 'Arts', classics: 'Classiques', nature: 'Nature', cook: 'Cuisine', home: 'Accueil',
    tagline: 'Le monde en 30 secondes. L\u2019info sans le bruit.',
    promise1: 'Rien que l\u2019info, v\u00E9rifi\u00E9e et sourc\u00E9e.',
    promise2: 'Demandez. Creusez. Comprenez.',
    prompt1: 'Que s\u2019est-il pass\u00E9 aujourd\u2019hui\u00A0?',
    prompt2: 'Mets-moi \u00E0 jour',
    prompt3: 'Quoi de neuf en Afrique francophone\u00A0?',
    talkTo: 'Parlez \u00E0 MIWO...',
    voice: 'Voix',
    sportLabel: 'Sport', sportTitle: 'Chaque match.\nChaque moment.',
    sportSub: 'Résultats en direct, analyses profondes et les histoires qui comptent. Des terrains de football aux circuits de course. Parce que le sport est comment nous comprenons le monde.',
    sportPlaceholder: 'Posez une question sur le sport, un match ou un athl\u00E8te...',
    historyLabel: 'Histoire', historyTitle: 'L\'histoire n\'est pas juste\nce qui s\'est passé.',
    historySub: 'Empires antiques, royaumes médiévaux, révolutions qui ont tout changé. Et les histoires que nous nous racontons sur pourquoi cela comptait. Comprendre le passé est le seul moyen de comprendre maintenant.',
    historyPlaceholder: 'Posez une question sur une \u00E9poque, un \u00E9v\u00E9nement ou un personnage...',
    classicsLabel: 'Classiques', classicsTitle: 'Tout ce qui est ancien\nest nouveau.',
    classicsSub: 'Rome et Gr\u00E8ce antiques. La philosophie qui r\u00E9sonne encore. La litt\u00E9rature qui a tout chang\u00E9. Des id\u00E9es d\u2019il y a des milliers d\u2019ann\u00E9es qui avaient tout compris, et nous essayons encore de comprendre ce qu\u2019elles voulaient dire.',
    classicsPlaceholder: 'Posez une question sur Rome, la Gr\u00E8ce, la philosophie, Platon, Aristote...',
    artsLabel: 'Arts et Culture', artsTitle: 'L\'art est comment nous\ncomprenons maintenant.',
    artsSub: 'Arts visuels, musique, théâtre, cinéma — ce qui nous rend humains. Des ouvertures de galeries aux mouvements qui ébranlent le monde. Parce que la culture est où tout se passe vraiment.',
    artsPlaceholder: 'Posez une question sur les arts, la musique, le th\u00E9\u00E2tre...',
    natureLabel: 'Nature', natureTitle: 'La planète parle.\nÉcoutons-nous?',
    natureSub: 'Climat. Océans. Forêts. Énergie. Les histoires environnementales qui changent tout. Racontées avec science. Pas de greenwashing. Pas de faux espoir. Juste ce qui se passe vraiment.',
    naturePlaceholder: 'Posez une question sur le climat, la biodiversit\u00E9, l\u2019\u00E9nergie...',
    cookLabel: 'Cuisine', cookTitle: 'Chaque repas raconte\nune histoire.',
    cookSub: 'Recettes, techniques, ingrédients — la culture, l\'histoire et la joie derrière ce que nous mangeons. Des repas rapides entre semaine aux traditions centenaires. Parce que la nourriture n\'est jamais juste de la nourriture.',
    cookPlaceholder: 'Posez une question sur les recettes, techniques, cuisine...',
    pantryTitle: 'Qu\u2019avez-vous dans la cuisine\u00A0?',
    pantrySub: 'Tapez vos ingr\u00E9dients s\u00E9par\u00E9s par des virgules ou touchez les puces.',
    pantryAdd: '+ Ajouter',
    pantryFind: 'Trouver des recettes',
    impressum: 'Mentions l\u00E9gales', legal: 'L\u00E9gal',
    allRights: 'Tous droits r\u00E9serv\u00E9s.',
    trademark: 'et le nom et logo MIWO sont des marques de Tindra Film GbR.',
    coFounder: 'Cofondateur/trice',
    miwoDesc: 'Mon Monde. Un service d\u2019intelligence m\u00E9diatique conversationnel.',
    allSport: 'Tous les Sports', allArts: 'Tous les Arts', allNature: 'Toute la Nature',
    allHistory: 'Toute l\u2019Histoire',
    you: 'Vous',
    stories: 'Articles',
    askMiwo: 'Demander \u00E0 MIWO',
    readMore: 'Lire la suite',
    askMiwoAbout: 'Demander \u00E0 MIWO',
    whatDoYouHave: 'Qu\u2019avez-vous\u00A0?',
    dailyFeature: 'Rubrique du jour',
    cowardsTitle: 'L\u00E2ches dont il faut se souvenir',
    cowardsSub: 'L\u2019histoire est pleine de h\u00E9ros. Elle est aussi pleine de gens qui savaient ce qui \u00E9tait juste, avaient le pouvoir d\u2019agir, et ont choisi de ne pas le faire.',
    backToBriefing: 'Retour au briefing',
    errorMessage: 'Quelque chose s\u2019est mal pass\u00E9. R\u00E9essayez dans un instant.',
  },
  ar: {
    sport: '\u0631\u064A\u0627\u0636\u0629', history: '\u062A\u0627\u0631\u064A\u062E', arts: '\u0641\u0646\u0648\u0646', classics: '\u0643\u0644\u0627\u0633\u064A\u0643\u064A\u0627\u062A', nature: '\u0637\u0628\u064A\u0639\u0629', cook: '\u0637\u0628\u062E', home: '\u0627\u0644\u0631\u0626\u064A\u0633\u064A\u0629',
    tagline: '\u0645\u062D\u0631\u0631\u0643 \u0627\u0644\u0625\u062E\u0628\u0627\u0631\u064A \u0627\u0644\u0645\u0648\u062B\u0648\u0642. \u0627\u0633\u0623\u0644\u0646\u064A \u0645\u0627\u0630\u0627 \u062D\u062F\u062B \u0627\u0644\u064A\u0648\u0645.',
    promise1: '\u0623\u062E\u0628\u0627\u0631 \u0641\u0642\u0637\u060C \u0645\u0648\u062B\u0642\u0629 \u0648\u0645\u0648\u062B\u0648\u0642\u0629.',
    promise2: '\u0627\u0633\u0623\u0644. \u062A\u0627\u0628\u0639. \u0627\u0641\u0647\u0645.',
    prompt1: '\u0645\u0627\u0630\u0627 \u062D\u062F\u062B \u0627\u0644\u064A\u0648\u0645\u061F',
    prompt2: '\u0623\u0639\u0637\u0646\u064A \u0627\u0644\u0645\u0644\u062E\u0635 \u0627\u0644\u0639\u0627\u0644\u0645\u064A',
    prompt3: '\u0645\u0627 \u0627\u0644\u062C\u062F\u064A\u062D \u0641\u064A \u0627\u0644\u0634\u0631\u0642 \u0627\u0644\u0623\u0648\u0633\u0637\u061F',
    talkTo: '\u062A\u062D\u062F\u062B \u0645\u0639 MIWO...',
    voice: '\u0635\u0648\u062A',
    sportLabel: '\u0631\u064A\u0627\u0636\u0629', sportTitle: '\u0643\u0644 \u0645\u0628\u0627\u0631\u0627\u0629\n\u062A\u0631\u0648\u064B \u0642\u0635\u0629.',
    sportSub: '\u0646\u062A\u0627\u0626\u062C \u0645\u0628\u0627\u0634\u0631\u0629 \u0648\u062A\u062D\u0644\u064A\u0644 \u0639\u0645\u064A\u0642.',
    sportPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0631\u064A\u0627\u0636\u0629...',
    historyLabel: '\u062A\u0627\u0631\u064A\u062E', historyTitle: '\u0645\u0627 \u062D\u062F\u062B\n\u0642\u0628\u0644\u0627\u064B \u0645\u0647\u0645.',
    historySub: '\u062D\u0636\u0627\u0631\u0627\u062A \u0642\u062F\u064A\u0645\u0629 \u0648\u062B\u0648\u0631\u0627\u062A \u062D\u062F\u064A\u062B\u0629.',
    historyPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0623\u064A \u062D\u0642\u0628\u0629 \u0623\u0648 \u062D\u062F\u062B...',
    classicsLabel: '\u0643\u0644\u0627\u0633\u064A\u0643\u064A\u0627\u062A', classicsTitle: '\u0643\u0644 \u0642\u062F\u064A\u0645\n\u062C\u062F\u064A\u062F \u0645\u0631\u0629 \u0623\u062E\u0631\u0649.',
    classicsSub: '\u0631\u0648\u0645\u0627 \u0648\u0627\u0644\u064A\u0648\u0646\u0627\u0646 \u0627\u0644\u0642\u062F\u064A\u0645\u0629. \u0641\u0644\u0633\u0641\u0629 \u0644\u0627 \u062A\u0632\u0627\u0644 \u062A\u0624\u062B\u0631. \u0623\u062F\u0628 \u063A\u064A\u0631 \u0643\u0644 \u0634\u064A\u0621.',
    classicsPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0631\u0648\u0645\u0627\u060C \u0627\u0644\u064A\u0648\u0646\u0627\u0646\u060C \u0627\u0644\u0641\u0644\u0633\u0641\u0629...',
    artsLabel: '\u0641\u0646\u0648\u0646 \u0648\u062B\u0642\u0627\u0641\u0629', artsTitle: '\u0644\u0648\u062D\u0629\n\u0627\u0644\u0639\u0627\u0644\u0645 \u0627\u0644\u064A\u0648\u0645.',
    artsSub: '\u0641\u0646\u0648\u0646 \u0628\u0635\u0631\u064A\u0629 \u0648\u0645\u0648\u0633\u064A\u0642\u0649 \u0648\u0645\u0633\u0631\u062D \u0648\u0633\u064A\u0646\u0645\u0627.',
    artsPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0641\u0646\u0648\u0646...',
    natureLabel: '\u0637\u0628\u064A\u0639\u0629', natureTitle: '\u0627\u0644\u0643\u0648\u0643\u0628 \u0644\u0627\n\u064A\u062F\u0648\u0631 \u0628\u0635\u0645\u062A.',
    natureSub: '\u0627\u0644\u0645\u0646\u0627\u062E \u0648\u0627\u0644\u062A\u0646\u0648\u0639 \u0627\u0644\u0628\u064A\u0648\u0644\u0648\u062C\u064A \u0648\u0627\u0644\u0637\u0627\u0642\u0629.',
    naturePlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0645\u0646\u0627\u062E \u0648\u0627\u0644\u0637\u0628\u064A\u0639\u0629...',
    cookLabel: '\u0637\u0628\u062E', cookTitle: '\u0643\u0644 \u0637\u0628\u0642\n\u0644\u0647 \u0642\u0635\u0629.',
    cookSub: '\u0648\u0635\u0641\u0627\u062A \u0648\u062Au0642\u0646\u064A\u0627\u062A \u0648\u0645\u0643\u0648\u0646\u0627\u062A.',
    cookPlaceholder: '\u0627\u0633\u0623\u0644 \u0639\u0646 \u0627\u0644\u0648\u0635\u0641\u0627\u062A...',
    pantryTitle: '\u0645\u0627\u0630\u0627 \u0639\u0646\u062F\u0643 \u0641\u064A \u0627\u0644\u0645\u0637\u0628\u062E\u061F',
    pantrySub: '\u0627\u0643\u062A\u0628 \u0627\u0644\u0645\u0643\u0648\u0646\u0627\u062A.',
    pantryAdd: '+ \u0625\u0636\u0627\u0641\u0629',
    pantryFind: '\u0627\u0628\u062D\u062B \u0639\u0646 \u0648\u0635\u0641\u0627\u062A',
    impressum: '\u0628\u064A\u0627\u0646\u0627\u062A \u0642\u0627\u0646\u0648\u0646\u064A\u0629', legal: '\u0642\u0627\u0646\u0648\u0646\u064A',
    allRights: '\u062C\u0645\u064A\u0639 \u0627\u0644\u062D\u0642\u0648\u0642 \u0645\u062D\u0641\u0648\u0638\u0629.',
    trademark: '',
    coFounder: '\u0645\u0624\u0633\u0633 \u0645\u0634\u0627\u0631\u0643',
    miwoDesc: '\u0639\u0627\u0644\u0645\u064A. \u062E\u062F\u0645\u0629 \u0625\u062E\u0628\u0627\u0631\u064A\u0629 \u0630\u0643\u064A\u0629.',
    allSport: '\u0643\u0644 \u0627\u0644\u0631\u064A\u0627\u0636\u0629', allArts: '\u0643\u0644 \u0627\u0644\u0641\u0646\u0648\u0646', allNature: '\u0643\u0644 \u0627\u0644\u0637\u0628\u064A\u0639\u0629',
    allHistory: '\u0643\u0644 \u0627\u0644\u062A\u0627\u0631\u064A\u062E',
    you: '\u0623\u0646\u062A',
    stories: '\u0645\u0642\u0627\u0644\u0627\u062A',
    askMiwo: '\u0627\u0633\u0623\u0644 MIWO',
    readMore: '\u0627\u0642\u0631\u0623 \u0627\u0644\u0645\u0632\u064A\u062F',
    askMiwoAbout: '\u0627\u0633\u0623\u0644 MIWO \u0639\u0646 \u0647\u0630\u0627',
    whatDoYouHave: '\u0645\u0627\u0630\u0627 \u0639\u0646\u062F\u0643\u061F',
    dailyFeature: '\u0632\u0627\u0648\u064A\u0629 \u0627\u0644\u064A\u0648\u0645',
    cowardsTitle: '\u062C\u0628\u0646\u0627\u0621 \u064A\u062C\u0628 \u0623\u0646 \u0646\u062A\u0630\u0643\u0631\u0647\u0645',
    cowardsSub: '\u0627\u0644\u062A\u0627\u0631\u064A\u062E \u0645\u0644\u064A\u0621 \u0628\u0627\u0644\u0623\u0628\u0637\u0627\u0644. \u0648\u0644\u0643\u0646\u0647 \u0645\u0644\u064A\u0621 \u0623\u064A\u0636\u0627\u064B \u0628\u0645\u0646 \u0639\u0631\u0641\u0648\u0627 \u0627\u0644\u0635\u0648\u0627\u0628 \u0648\u0644\u0645 \u064A\u0641\u0639\u0644\u0648\u0627.',
    backToBriefing: '\u0627\u0644\u0639\u0648\u062F\u0629 \u0625\u0644\u0649 \u0627\u0644\u0645\u0644\u062E\u0635',
    errorMessage: '\u062D\u062F\u062B \u062E\u0637\u0623. \u062D\u0627\u0648\u0644 \u0645\u0631\u0629 \u0623\u062E\u0631\u0649.',
  },
};

const SUPPORTED_LANGS = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'de', label: 'DE', name: 'Deutsch' },
  { code: 'es', label: 'ES', name: 'Espa\u00F1ol' },
  { code: 'fr', label: 'FR', name: 'Fran\u00E7ais' },
  { code: 'ar', label: '\u0639\u0631', name: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629' },
];

const LangContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export function LangProvider({ children }) {
  const [lang, setLangState] = useState('en');

  useEffect(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('miwo-lang') : null;
    if (saved && translations[saved]) setLangState(saved);
  }, []);

  const setLang = (code) => {
    setLangState(code);
    if (typeof window !== 'undefined') localStorage.setItem('miwo-lang', code);
  };

  const t = (key) => {
    return (translations[lang] && translations[lang][key]) || (translations.en && translations.en[key]) || key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, SUPPORTED_LANGS }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}

export function LangPicker() {
  const { lang, setLang, SUPPORTED_LANGS } = useLang();

  return (
    <div className="lang-picker">
      {SUPPORTED_LANGS.map((l) => (
        <button
          key={l.code}
          className={`lang-btn ${lang === l.code ? 'active' : ''}`}
          onClick={() => setLang(l.code)}
          title={l.name}
        >
          {l.label}
        </button>
      ))}
    </div>
  );
}
